id: P009340
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:34:14.055614
source_metadata:
  id: bdr:W10247
  title: བསྟན་རྩིས་གསལ་བའི་ཉིན་བྱེད
  author: ''
  volumes:
    c701975d8b1f48a8affde1a76a0301fd:
      image_group_id: I4277
      title: ''
      volume_number: 1
      total_pages: 374
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
