id: I48A355F6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T21:55:53+00:00'
last_modified: '2022-06-08T10:19:21.130889+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W10247
  title: བསྟན་རྩིས་གསལ་བའི་ཉིན་བྱེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6084':
      image_group_id: I4277
      title: ''
      total_pages: 374
      order: 1
      base_file: 6084.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
